---
- name: Install apache httpd
  hosts: ce_ansible_host
  gather_facts: true
  become: true
  vars: 
    port: 8080

  tasks:
    - name: update package manager
      become: true
      apt:
        upgrade: yes

    - name: Print all gather_facts
      debug:
        msg: "{{ ansible_facts }}"

    - name: Install nginx
      become: true
      apt:
        name: nginx
        state: present
      notify:
        - Restart Apache

    - name: Install apache httpd
      become: true
      apt:
        name: apache2
        state: present

    - name: Install the latest version of Apache
      ansible.builtin.apt:
        name: apache2
        state: latest
      # notify:
      #   - Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
      